name = "Walsh"
uuid = "f1c6acf7-8ab3-4e4a-9b0e-68ce1a4a1adb"
authors = ["Shuhei Yoshida <yshuhei@ele.kindai.ac.jp> and contributors"]
version = "0.1.0"

[deps]
Hadamard = "4a05ff16-5f95-55f4-bb53-bb3f467c689a"

[compat]
julia = "1.6, 1.7, 1.8, 1.9, 1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
