name = "Walsh"
uuid = "cfe0385d-7122-40ce-b1fd-a530b8064ad3"
authors = ["Shuhei Yoshida <yshuhei@ele.kindai.ac.jp> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
